# Generated by Django 5.2.5 on 2025-09-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='ingredients',
            new_name='Description',
        ),
    ]
